### ISSUE TITLE
Front Camera 전면 카메라는 사용 불가한가요?

### ISSUE THREAD

**Issue by soultaffy** [ParkSangGwon/TedPicker#25]
Poly Picker 를 사용하기위해 찾아보다가 넘어오게 되었는데요
블로그도 잘 보고 있는 1인입니다. ㅎ
Poly Picker보다 사용법이 쉽게 잘만들어주셨더군요. 감사합니다.

Picker 액티비티를 실행했을 때 
카메라 탭에서 기본 카메라로 전면 카메라를 쓰고 싶은데 
커스텀 세팅이 가능할까요?
혹은 추후 전면카메라 전환 버튼 같은 걸 추가하실 계획이 있으신지 궁금합니다.

on 'CAMERA' tab, I want change default camera to front one.
Can I customize?

**Comment by mick1418** [comment]
That would be a very useful feature!
+1 on this one

**Comment by ParkSangGwon** [comment]
@soultaffy @mick1418 
Ok, I will add method for front camera mode
