### ISSUE TITLE
Rearrange selected images 'Gallery'

### ISSUE THREAD

**Issue by summers314** [ParkSangGwon/TedPicker#3]
Hi. Im trying to rearrange the selected images from the gallery before passing them back to my original activity. Any suggestions?

**Comment by ParkSangGwon** [comment]
@summers314 what is your rearrange's condition?

when you receive ArrayList at `onActivityResult()` in your activity, you can rearrange

**Comment by summers314** [comment]
Yup. Its not a problem with the library. Presently onActvityResult we only get FilePath/Uri; I required more parameters like DATE_TAKEN etc. I solved this.
