### ISSUE TITLE
Failed to resolve cwac camera 0.6.+

### ISSUE THREAD

**Issue by mgursch** [ParkSangGwon/TedPicker#35]
Please maintain the library to solve this issue.

"Error:Failed to resolve: com.commonsware.cwac:camera:0.6.+"

Currently im only able to build my app with "gradle offline work" - when im using another machine i will possibly not be able to build my app, because is no offline cached version of cwac camera.

Thanks

**Comment by MartSerra** [comment]
Note that the __READ_ME.md__ file has the wrong URL.
The correct URL for cwac camera is __https://s3.amazonaws.com/repo.commonsware.com__ instead of _https://repo.commonsware.com.s3.amazonaws.com_.
I will submit an issue to @ParkSangGwon to change this on his repo.

**Comment by Smiacter** [comment]
Thanks MartSerra, that works

**Comment by mgursch** [comment]
Thanks for the hint :)
