### ISSUE TITLE
Run time permissions 

### ISSUE THREAD

**Issue by Ahmed-Mostafa-Ghanayem** [ParkSangGwon/TedPicker#40]
Please add run time permission check in you lib.
Thank you.

**Comment by ParkSangGwon** [comment]
@Ahmed-Mostafa-Ghanayem 
I already published runtime permission library  [TedPermission](https://github.com/ParkSangGwon/TedPermission)
Thank you.

**Comment by Ahmed-Mostafa-Ghanayem** [comment]
**Thank you.**
I will have a look on it.
