### ISSUE TITLE
Image Select Toolbar doesn't show up.

### ISSUE THREAD

**Issue by vj-1023** [ParkSangGwon/TedPicker#7]
@ParkSangGwon , @gun0912 
I did all according to the instructions provided for some reason the toolbar to select image isn't appearing in my application, kindly check the screenshot below

![image](https://cloud.githubusercontent.com/assets/12961547/13011421/bccdbf58-d1cc-11e5-9471-37e7e437ea0f.png)

Another issue which i m facing is with the camera activity, whenever i click an image, it comes below in the selected images list perfectly but the camera is just still showing the same image, it doesn't refresh itself to click another one, or turns into a black screen and the capture button doesn't do anthing.

**Comment by enggazzar** [comment]
i solved this problem by
include toolbar at layout picker_activity_main_pp
at activity ImagePickerActivity
 Toolbar toolbar = (Toolbar) findViewById(R.id.toolbarcam);
        setSupportActionBar(toolbar);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
       // getSupportActionBar().setTitle(getString(R.string.title_activity_details));
        toolbar.setNavigationOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // Log.e("Strgg","kk");
                onBackPressed();
            }
        });
work with me

**Comment by vj-1023** [comment]
But I have just directly used the gradle build import ! How do I change the
library files ?

Cheers,
  Vinit

**Comment by enggazzar** [comment]
import module of library tell you can modify

**Comment by vj-1023** [comment]
Can you please tell me the procedure ?
I m using Android studio and I m new to Android and I really want to crack
this.

Cheers,
  Vinit

**Comment by enggazzar** [comment]
file-new-import module
choose tedpicker library aftere u download the project

**Comment by enggazzar** [comment]
then file projectstructure  click app then dependancies

**Comment by enggazzar** [comment]
then add module dependancy
choose tedpicker library

**Comment by vj-1023** [comment]
Thank you soo much, I will try it out and get back to you if I get stuck
somewhere brother.

Cheers,
  Vinit

**Comment by ParkSangGwon** [comment]
@vj-1023 do you use Appcompat Theme?
and declare like this code?
`
<item name="windowActionBar">false</item>
<item name="windowNoTitle">true</item>
`

**Comment by vj-1023** [comment]
I m using mainActivity extends  AppCompactActivity , and my theme is
myAppTheme which is the parent theme of  AppCompactActivity.NoActionBar

Where do I add this code ?

@vj-1023 <https://github.com/vj-1023> do you use Appcompat Theme?
and declare like this code?

<item name="windowActionBar">false</item>
<item name="windowNoTitle">true</item>

—
Reply to this email directly or view it on GitHub
<https://github.com/ParkSangGwon/TedPicker/issues/7#issuecomment-184485644>.

**Comment by ParkSangGwon** [comment]
@vj-1023 

you have to use AppCompat theme like this. ImagePickerActivity use toolbar without actionbar

```javascript
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>


        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>

```
