### ISSUE TITLE
Fatal error on pressing the image capture button with Samsung Galaxy S3 Neo

### ISSUE THREAD

**Issue by ArcherN9** [ParkSangGwon/TedPicker#8]
With the library integrated and working on every device I have, the app crashes with a `OutOfMemoryError` when the 'image capture' is pressed on the Samsung Galaxy S3 Neo device.

Model Number : GT I9300I
Android version : 4.3

Stacktrace : 

> FATAL EXCEPTION: Thread-1859
>                                                 java.lang.OutOfMemoryError
>                                                     at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
>                                                     at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:512)
>                                                     at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:530)
>                                                     at com.gun0912.tedpicker.CwacCameraFragment$MyCameraHost.saveImage(CwacCameraFragment.java:476)
>                                                     at com.commonsware.cwac.camera.ImageCleanupTask.run(ImageCleanupTask.java:166)

**Comment by ParkSangGwon** [comment]
yes, some low memory device can occur 'outOfMemoryError'.
I will find solution for handling this error

**Comment by obaidjatoi** [comment]
Hello , 
Please solve the issue of OUT OF MEMORY ERROR !! Or tell me how to handle it.

**Comment by inetaa** [comment]
@ParkSangGwon Experienced the same issue on Samsung Galaxy A3. Any solutions already?

**Comment by jinesh08** [comment]
Same problem in samsung
