### ISSUE TITLE
error: cannot find symbol variable abc_ic_ab_back_mtrl_am_alpha

### ISSUE THREAD

**Issue by davidpini** [ParkSangGwon/TedPicker#9]
The name of the resource was changed in the 23.2.0 support library.

 `abc_ic_ab_back_mtrl_am_alpha` to `abc_ic_ab_back_material`

**Comment by stefanopassador** [comment]
Same problem here!

**Comment by ParkSangGwon** [comment]
Thanks.
Now that problem fixed.
we will use own `clear icon` instead of `abc_ic_ab_back_mtrl_am_alpha`
fixed at v1.0.10.
